changelog:
  categories:
    - title: "🚀 Features & Improvements"
      labels:
        - "enhancement"
        - "feature"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🧰 Maintenance & Dependencies"
      labels:
        - "dependencies"
        - "chore"
        - "documentation"
